# Generated by Django 3.2 on 2021-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.CharField(max_length=200)),
                ('short_link', models.CharField(max_length=50, unique=True)),
                ('redirects', models.IntegerField(default=0)),
            ],
        ),
    ]
