# Generated by Django 2.2.15 on 2021-06-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20210528_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='link',
            name='full_link',
            field=models.CharField(max_length=200, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='redirects',
            field=models.IntegerField(default=0, verbose_name='Редиректы'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=50, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
